export const APPLICATION_LIST_MY_REQUEST = 'APPLICATION_LIST_MY_REQUEST'
export const APPLICATION_LIST_MY_SUCCESS = 'APPLICATION_LIST_MY_SUCCESS'
export const APPLICATION_LIST_MY_FAIL = 'APPLICATION_LIST_MY_FAIL'
export const APPLICATION_LIST_MY_RESET = 'APPLICATION_LIST_MY_RESET'

export const APPLICATION_DETAILS_REQUEST = 'APPLICATION_DETAILS_REQUEST'
export const APPLICATION_DETAILS_SUCCESS = 'APPLICATION_DETAILS_SUCCESS'
export const APPLICATION_DETAILS_FAIL = 'APPLICATION_DETAILS_FAIL'
export const APPLICATION_DETAILS_RESET = 'APPLICATION_DETAILS_FAIL'

export const APPLICATION_CREATE_REQUEST = 'APPLICATION_CREATE_REQUEST'
export const APPLICATION_CREATE_SUCCESS = 'APPLICATION_CREATE_SUCCESS'
export const APPLICATION_CREATE_FAIL = 'APPLICATION_CREATE_FAIL'
export const APPLICATION_CREATE_RESET = 'APPLICATION_CREATE_RESET'

export const APPLICANT_LIST_REQUEST = 'APPLICANT_LIST_REQUEST'
export const APPLICANT_LIST_SUCCESS = 'APPLICANT_LIST_SUCCESS'
export const APPLICANT_LIST_FAIL = 'APPLICANT_LIST_FAIL'
export const APPLICANT_LIST_RESET = 'APPLICANT_LIST_RESET'

export const APPLICATION_UPDATE_REQUEST = 'APPLICATION_UPDATE_REQUEST'
export const APPLICATION_UPDATE_SUCCESS = 'APPLICATION_UPDATE_SUCCESS'
export const APPLICATION_UPDATE_FAIL = 'APPLICATION_UPDATE_FAIL'
export const APPLICATION_UPDATE_RESET = 'APPLICATION_UPDATE_RESET'