export const JOB_OPENING_LIST_REQUEST = 'JOB_OPENING_LIST_REQUEST'
export const JOB_OPENING_LIST_SUCCESS = 'JOB_OPENING_LIST_SUCCESS'
export const JOB_OPENING_LIST_FAIL = 'JOB_OPENING_LIST_FAIL'

export const JOB_OPENING_LIST_MY_REQUEST = 'JOB_OPENING_LIST_MY_REQUEST'
export const JOB_OPENING_LIST_MY_SUCCESS = 'JOB_OPENING_LIST_MY_SUCCESS'
export const JOB_OPENING_LIST_MY_FAIL = 'JOB_OPENING_LIST_MY_FAIL'
export const JOB_OPENING_LIST_MY_RESET = 'JOB_OPENING_LIST_MY_RESET'

export const JOB_OPENING_DETAILS_REQUEST = 'JOB_OPENING_DETAILS_REQUEST'
export const JOB_OPENING_DETAILS_SUCCESS = 'JOB_OPENING_DETAILS_SUCCESS'
export const JOB_OPENING_DETAILS_FAIL = 'JOB_OPENING_DETAILS_FAIL'

export const JOB_OPENING_CREATE_COMMENT_REQUEST = 'JOB_OPENING_CREATE_COMMENT_REQUEST'
export const JOB_OPENING_CREATE_COMMENT_SUCCESS = 'JOB_OPENING_CREATE_COMMENT_SUCCESS'
export const JOB_OPENING_CREATE_COMMENT_FAIL = 'JOB_OPENING_CREATE_COMMENT_FAIL'
export const JOB_OPENING_CREATE_COMMENT_RESET = 'JOB_OPENING_CREATE_COMMENT_RESET'

export const JOB_OPENING_DELETE_REQUEST = 'JOB_OPENING_DELETE_REQUEST'
export const JOB_OPENING_DELETE_SUCCESS = 'JOB_OPENING_DELETE_SUCCESS'
export const JOB_OPENING_DELETE_FAIL = 'JOB_OPENING_DELETE_FAIL'

export const JOB_OPENING_CREATE_REQUEST = 'JOB_OPENING_CREATE_REQUEST'
export const JOB_OPENING_CREATE_SUCCESS = 'JOB_OPENING_CREATE_SUCCESS'
export const JOB_OPENING_CREATE_FAIL = 'JOB_OPENING_CREATE_FAIL'
export const JOB_OPENING_CREATE_RESET = 'JOB_OPENING_CREATE_RESET'

export const JOB_OPENING_UPDATE_REQUEST = 'JOB_OPENING_UPDATE_REQUEST'
export const JOB_OPENING_UPDATE_SUCCESS = 'JOB_OPENING_UPDATE_SUCCESS'
export const JOB_OPENING_UPDATE_FAIL = 'JOB_OPENING_UPDATE_FAIL'
export const JOB_OPENING_UPDATE_RESET = 'JOB_OPENING_UPDATE_RESET'

export const JOB_OPENING_VERIFY_REQUEST = 'JOB_OPENING_VERIFY_REQUEST'
export const JOB_OPENING_VERIFY_SUCCESS = 'JOB_OPENING_VERIFY_SUCCESS'
export const JOB_OPENING_VERIFY_FAIL = 'JOB_OPENING_VERIFY_FAIL'
export const JOB_OPENING_VERIFY_RESET = 'JOB_OPENING_VERIFY_RESET'