export const RECRUITER_LOGIN_REQUEST = 'RECRUITER_LOGIN_REQUEST'
export const RECRUITER_LOGIN_SUCCESS = 'RECRUITER_LOGIN_SUCCESS'
export const RECRUITER_LOGIN_FAIL = 'RECRUITER_LOGIN_FAIL'
export const RECRUITER_LOGOUT = 'RECRUITER_LOGOUT'

export const RECRUITER_GENERATE_OTP_REQUEST = 'RECRUITER_GENERATE_OTP_REQUEST'
export const RECRUITER_GENERATE_OTP_SUCCESS = 'RECRUITER_GENERATE_OTP_SUCCESS'
export const RECRUITER_GENERATE_OTP_FAIL = 'RECRUITER_GENERATE_OTP_FAIL'
export const RECRUITER_GENERATE_OTP_RESET = 'RECRUITER_GENERATE_OTP_RESET'

export const RECRUITER_REGISTER_REQUEST = 'RECRUITER_REGISTER_REQUEST'
export const RECRUITER_REGISTER_SUCCESS = 'RECRUITER_REGISTER_SUCCESS'
export const RECRUITER_REGISTER_FAIL = 'RECRUITER_REGISTER_FAIL'

export const RECRUITER_VERIFICATION_REQUEST = 'RECRUITER_VERIFICATION_REQUEST'
export const RECRUITER_VERIFICATION_SUCCESS = 'RECRUITER_VERIFICATION_SUCCESS'
export const RECRUITER_VERIFICATION_FAIL = 'RECRUITER_VERIFICATION_FAIL'

export const RECRUITER_DETAILS_REQUEST = 'RECRUITER_DETAILS_REQUEST'
export const RECRUITER_DETAILS_SUCCESS = 'RECRUITER_DETAILS_SUCCESS'
export const RECRUITER_DETAILS_FAIL = 'RECRUITER_DETAILS_FAIL'
export const RECRUITER_DETAILS_RESET = 'RECRUITER_DETAILS_RESET'

export const RECRUITER_UPDATE_PROFILE_REQUEST = 'RECRUITER_UPDATE_PROFILE_REQUEST'
export const RECRUITER_UPDATE_PROFILE_SUCCESS = 'RECRUITER_UPDATE_PROFILE_SUCCESS'
export const RECRUITER_UPDATE_PROFILE_FAIL = 'RECRUITER_UPDATE_PROFILE_FAIL'
export const RECRUITER_UPDATE_PROFILE_RESET = 'RECRUITER_UPDATE_PROFILE_RESET'

export const RECRUITER_LIST_REQUEST = 'RECRUITER_LIST_REQUEST'
export const RECRUITER_LIST_SUCCESS = 'RECRUITER_LIST_SUCCESS'
export const RECRUITER_LIST_FAIL = 'RECRUITER_LIST_FAIL'
export const RECRUITER_LIST_RESET = 'RECRUITER_LIST_RESET'

export const RECRUITER_DELETE_REQUEST = 'RECRUITER_DELETE_REQUEST'
export const RECRUITER_DELETE_SUCCESS = 'RECRUITER_DELETE_SUCCESS'
export const RECRUITER_DELETE_FAIL = 'RECRUITER_DELETE_FAIL'

export const RECRUITER_VERIFY_AS_ADMIN_REQUEST = 'RECRUITER_VERIFY_AS_ADMIN_REQUEST'
export const RECRUITER_VERIFY_AS_ADMIN_SUCCESS = 'RECRUITER_VERIFY_AS_ADMIN_SUCCESS'
export const RECRUITER_VERIFY_AS_ADMIN_FAIL = 'RECRUITER_VERIFY_AS_ADMIN_FAIL'
export const RECRUITER_VERIFY_AS_ADMIN_RESET = 'RECRUITER_VERIFY_AS_ADMIN_RESET'